### ISSUE TITLE
AssertionError  : assert len(data_gt[i]) == len(data_out[i])

### ISSUE THREAD

**Issue by KevinJeon** [mks0601/PoseFix_RELEASE#10]
Does the number of object detection in the test on train set might be different from the number of object detection in the ground truth?

**Comment by mks0601** [comment]
can you tell me where is that assertion?

**Comment by KevinJeon** [comment]
thanks for your comment. Its' in lib/tfflat/base.py line 307!

**Comment by mks0601** [comment]
How do you train? That block is to use testing result of any other pose estimation model on the training set. That result is used when PoseFix try to synthesize not annotated joint in the training set. For example, in COCO dataset, some joints are not annotated. So, I use other pose estimation method's result when synthesize of not annotated joint. If you place `result.json` in `test_on_trainset` like README, there should be no problem.

**Comment by KevinJeon** [comment]
I use my own dataset, and I use the _result.json_ of hrnet model. it emerges error like the length of gt is 7, and length of out is 6. And Actual Image has 7 objects, but test result(hrnet) of image detect the 6 objects.

**Comment by mks0601** [comment]
You should test your method using groundtruth bbox on the training set.

**Comment by KevinJeon** [comment]
thks for your coment! :)
