### ISSUE TITLE
About backbones

### ISSUE THREAD

**Issue by pzn666** [mks0601/PoseFix_RELEASE#11]
Thanks to your brilliant works in PoseFix, but I wonder if I change the backbone from resnet152 to stacked hourglass (maybe 2 stacks) will the performance get better? Really appreciate your reply.

**Comment by mks0601** [comment]
Hi, personally, I think ResNet would be better than hourglass because recent 2d human pose estimation methods such as [TF-SimpleHumanPose](https://github.com/mks0601/TF-SimpleHumanPose) achieve better accuracy than hourglass. Why do you need to apply hourglass?

**Comment by pzn666** [comment]
Hi, the reason why I am trying to apply hourglass is our project already has a hourglass backbone for other purpose, so I am thinking just using the synthetic part in the paper. And also, I'm wondering can the idea of posefix applys on some regular 2d bbox detection for refinement or not? Thx for ur reply.

**Comment by mks0601** [comment]
I think you should try, but as I said, in my opinion, I think ResNet would be better. 

Also, can you clarify which idea do you want to use?

If that is model-agnostic refinement, PoseFix assumes existing methods have similar error distribution as analyzed in [Ronchi etal](http://openaccess.thecvf.com/content_ICCV_2017/papers/Ronchi_Benchmarking_and_Error_ICCV_2017_paper.pdf). If you can categorize object detection error and analyze error of several methods, which should have similar error distribution, then, model-agnostic refinement can work.

If that is just synthetic error augmentation based on your defined bbox jittering, that is just a data augmentation. It should work, especially can prevent overfitting, but I wonder that could have a big meaning or contribution.

**Comment by pzn666** [comment]
Thank you, I will give it a try
