### ISSUE TITLE
Some Question About the Train.py

### ISSUE THREAD

**Issue by 571502680** [mks0601/PoseFix_RELEASE#12]
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[4] = [0, 0, 159, 4] does not index into shape [16,96,72,17]
	 [[{{node tower_0/ScatterNd}}]]

During handling of the above exception, another exception occurred:

**Comment by mks0601** [comment]
Hi, I committed a new version right before. Can you check and run again?

**Comment by 571502680** [comment]
Yes, i solved it !how does it show the visualization of the result？

**Comment by mks0601** [comment]
You can set `vis=True` in `test.py`

**Comment by HuangJunJie2017** [comment]
@571502680 how did you solve the problem?
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[4] = [0, 0, 159, 4] does not index into shape [16,96,72,17]
