### ISSUE TITLE
How to test on COCO test-set

### ISSUE THREAD

**Issue by ustcjinggg** [mks0601/PoseFix_RELEASE#15]
Glad you share the code of your intersting work .
May I ask how to test your result on COCO2017 test-set cause I couldn't find keypoint annotations of COCO test-set or deliver my result of test-set in the http://cocodataset.org/#home .
I'd appreciate if you could share the annotations or show me how to find it.

**Comment by mks0601** [comment]
Hi, COCO does not provide annotation for test set. You have to use CodaLab following http://cocodataset.org/#guidelines

**Comment by ustcjinggg** [comment]
Thanks!
