### ISSUE TITLE
Have you treid to fix the result from posefix?

### ISSUE THREAD

**Issue by ustcjinggg** [mks0601/PoseFix_RELEASE#18]
I wondered if posefix could continue fix the output from posefix.

**Comment by mks0601** [comment]
Yes, actually I tried this before paper submission. Unfortunately, the performance decreases when trying to refine the output of the PoseFix. I think this is because the pose distribution of the PoseFix's output is different from other usual pose estimators.

**Comment by gongzaizhou** [comment]
I try fix the output from posefix, but it has error of 'IndexError: list index out of range' in 286th line of base.py

**Comment by gongzaizhou** [comment]
I find 'image_id' in the output of posefix less than your provide json file, this affects  fix the output from posefix?
