### ISSUE TITLE
How do you use the error statistics as prior information?

### ISSUE THREAD

**Issue by ustcjinggg** [mks0601/PoseFix_RELEASE#19]
There is a problem bothering me after reading your interesting work.
You said "We use this error statistics as prior infromation to generate synthetic posese and use the synthesized poses to train our model" in Abatract. While you use the output heatmaps from other model as input to generate a better poses result, but what is this to do with "error statistics distribution"?
Looking forward to you reply, thanks!

**Comment by mks0601** [comment]
If you read the paper fully, you can find what the statistics means. Could you read the introduction section?
