### ISSUE TITLE
Can you provide hrnet pre_trained models?

### ISSUE THREAD

**Issue by gongzaizhou** [mks0601/PoseFix_RELEASE#20]

**Comment by mks0601** [comment]
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch

**Comment by gongzaizhou** [comment]
> https://github.com/leoxiaobin/deep-high-resolution-net.pytorch

This is  pytorch  implementation, would you like to share your tensorflow implementation?

**Comment by mks0601** [comment]
I'm not the author of HRNet, so I don't know. I used the pytorch implementation.

**Comment by gongzaizhou** [comment]
posefix+HRNet is AP 76.7, this posefix trained in resnet-152 or hrnet?

**Comment by mks0601** [comment]
resnet 152
