### ISSUE TITLE
No such file or directory: 'tmp_result_0.pkl'

### ISSUE THREAD

**Issue by gongzaizhou** [mks0601/PoseFix_RELEASE#21]
‘ please prepare human detection result and input pose properly’，where the 'human detection result file'  should be placed?

**Comment by gongzaizhou** [comment]
' The pkl files are generated and deleted automatically in testing stage, so you don't have to prepare them', why I need to prepare human detection result?

**Comment by mks0601** [comment]
That is typo. You don't have to prepare human detection result. Only input pose is required.

**Comment by gongzaizhou** [comment]
> That is typo. You don't have to prepare human detection result. Only input pose is required.
thanks for your rely!

**Comment by gongzaizhou** [comment]
my json file malformed or other reason?

**Comment by gongzaizhou** [comment]
MS COCO format for keypoint detection is 
'[{
"image_id" : int, 
"category_id" : int, 
"keypoints" : [x1,y1,v1,...,xk,yk,vk], 
"score" : float,
}]' ,
my json file need to add 'bbox' key?

**Comment by mks0601** [comment]
Please describe your problem in a more detailed way.

**Comment by gongzaizhou** [comment]
How do I solve "No such file or directory: 'tmp_result_0.pkl'"?, I have rename 'input_pose/name_of_input_pose.json' in dataset.py.

**Comment by mks0601** [comment]
Please check 34th line of `data/COCO/dataset.py`. There, you should change input pose file name.

**Comment by gongzaizhou** [comment]
> Please check 34th line of `data/COCO/dataset.py`. There, you should change input pose file name.
I have change pose file name from 'person_keypoints_test-dev2017_Simple152_results.json' to 'keypoints_val2017_results_0.json'  in `data/COCO/dataset.py` , but still 'No such file or directory: 'tmp_result_0.pkl' error.

**Comment by mks0601** [comment]
I think you should change `testset` in `config.py` to `val` or `test`. Did you check?

**Comment by gongzaizhou** [comment]
Sorry, it's my pot. I forget to updata chaged from my ide. thanks for your reply very much!  I solved this problem.

**Comment by gongzaizhou** [comment]
Sorry, it's my pot. I forget to update changed from my ide. thanks for your reply very much! I solved this problem.

**Comment by mks0601** [comment]
Good for you!

**Comment by ankitsharma07** [comment]
I am trying to test this for a single image and according to that converted the image annotation into coco format.
When i provided the input pose for the same i am getting this error.

`FileNotFoundError: [Errno 2] No such file or directory: 'tmp_result_0.pkl'`

How do we test for single image?
