### ISSUE TITLE
A question about the input results

### ISSUE THREAD

**Issue by HeathHose** [mks0601/PoseFix_RELEASE#23]
Whether the results of test_on_trainset and input_pose need rescore and oks_nms processing?
I trained the Pose Fix with res152 and default parameters, but the metric was reduced by 0.1.  I think it may be that the input pose results have been treated as above.

**Comment by HeathHose** [comment]
I used the HRNet code. I added bbox and rescore box when I generated the test_on_trainset results, rescore and oks_nms the results when the input pose on test datasets.

**Comment by mks0601** [comment]
I don't think removing rescoring and oks_nms in `test_on_trainset` and `input_pose` would hurt the accuracy of the PoseFix. You can just use pre-trained PoseFix, which is provided in README. Also, for the `test_on_trainset`, you can just download it in README. Could you try again with provided files again?

**Comment by HeathHose** [comment]
Thank you very much for your reply. I have tested that **oks_nms** has no hurt the accuracy of PoseFix, and I will test your original results with your methods. It may be that the results I have generated by other method are saturated, and it is difficult for PoseFix to further improve it.

**Comment by HeathHose** [comment]
> I don't think removing rescoring and oks_nms in `test_on_trainset` and `input_pose` would hurt the accuracy of the PoseFix. You can just use pre-trained PoseFix, which is provided in README. Also, for the `test_on_trainset`, you can just download it in README. Could you try again with provided files again?

Thank you very much for your reply. I have tested that **oks_nms** has no hurt the accuracy of PoseFix, and I will test your original results with your methods. It may be that the results I have generated by other method are saturated, and it is difficult for PoseFix to further improve it.
