### ISSUE TITLE
Getting test result for single image input

### ISSUE THREAD

**Issue by ankitsharma07** [mks0601/PoseFix_RELEASE#24]
Hi! I was trying to run the model for single image for the testing how it works. Initially it showed the `tmp_result.pkl` file not found error which I solved by removing the dependency of the code on temporary results.

I am having my input image in coco dataset format yet i am facing this error while running the code now I get the following error.
Is there a specific way to get rid of this error??

![Screenshot from 2019-09-06 19-10-39](https://user-images.githubusercontent.com/12720159/64432439-23962080-d0da-11e9-9be7-c1e9905431ef.png)

**Comment by mks0601** [comment]
Please read README. This issue has been raised by other users and solution is described in README. `tmp_result.pkl` is just a temporary file automatically generated in testing stage. You should not delete that code. This error almost always happen when there is a bug in data loading part. Please prepare your dataset into coco format EXACTLY.
