### ISSUE TITLE
About Output shape

### ISSUE THREAD

**Issue by ghost** [mks0601/PoseFix_RELEASE#28]
Thank your implementation.
I have a question about input shape. I looked into the code in main/config.py as below
![stride](https://user-images.githubusercontent.com/16331519/65510668-1796c500-df08-11e9-9e94-85798ee29b37.PNG)
The question is why out_shape is input_shape // 4 ?
If I remembered correctly, the input shape size ( width, height ) will be 8 times smaller (width/8, height/8) after feeding it to Resnet network. It confused me a lot time :(.  Thank you.

**Comment by mks0601** [comment]
The output of resnet is //32, //32. I use three 2x deconvolutional layer to upsample it by 8, which becomes //4, //4. For more information, please read my paper.
