### ISSUE TITLE
 Question about  'output/model_dump/MPII/*'

### ISSUE THREAD

**Issue by YJLeonMan** [mks0601/PoseFix_RELEASE#32]
thank u for you time, how i can download  the trained model files,please

**Comment by mks0601** [comment]
You can download at README

**Comment by YJLeonMan** [comment]
oh thank u ,but README provide COCO and PoseTrack model , not have MPII , Did I need to train myself?

**Comment by mks0601** [comment]
Oh I haven't trained models on MPII dataset. Maybe you can try.
