### ISSUE TITLE
input pose

### ISSUE THREAD

**Issue by carlottaruppert** [mks0601/PoseFix_RELEASE#33]
I have troubles understanding how exactly to prepare the input pose. What is the difference in between the test_on_trainset_path and input_pose_path (line 33 and 34 in dataset.py)?
I would like to test with your provided keypoint results, which I got from your result section, but I'm unsure on where to put them. I tried both ...input_pose/test_on_trainset/result.json and ...input_pose/person_keypoints_test-dev2017_Simple152_results.json

But unfortunatly I'm getting the No such file or directory 'tmp_results_0.pkl' mistake which indicates that I didn't prepare the input pose as needed. 

I tried all different testsets too ( train, val, test in config.py).

In the end I would like to implement your code in combination with HRNet, but just wanted to get it up and running with your provided results first. 

Thanks in advance!

**Comment by mks0601** [comment]
In the readme, 


Train
input_pose/test_on_trainset/result.json should be prepared before training. This is test result on the training set with the groundtruth bbox and used when synthesizing input pose of not annotated keypoints in the training stage. Testing result of TF-SimpleHumanPose is used.



Test
input_pose/name_of_input_pose.json is pose estimation result of any other method. You have to rename the it and also input_pose_path of the data/$DATASET/dataset.py. The input_pose/name_of_input_pose.json should be follow MS COCO format. To test on the PoseTrack dataset, run tool/posetrack2coco_output.py before testing to convert PoseTrack output files to COCO format.

**Comment by mks0601** [comment]
In the readme,

Troubleshoot
2. For those who suffer from FileNotFoundError: [Errno 2] No such file or directory: 'tmp_result_0.pkl' in testing stage, please prepare input pose properly. The pkl files are generated and deleted automatically in testing stage, so you don't have to prepare them. Most of this error comes from inproper human detection file.

**Comment by mks0601** [comment]
Hope this is helpful.

**Comment by carlottaruppert** [comment]
Oh I'm sorry I overread the test part somehow. Thanks for making it clear!
