### ISSUE TITLE
How much does the compute_iou bug affect the final AP?

### ISSUE THREAD

**Issue by hbin-ac** [mks0601/PoseFix_RELEASE#34]
Can you tell me? Thank you very much!

**Comment by mks0601** [comment]
I think it would effect very marginally. The output of that function is used when synthesizing input pose of 'swap' error in training stage. Actually, most of the pose error of other pose methods are jitter and miss. 'swap' error takes very small portion, so I think that would not effect overall performance very much.

**Comment by hbin-ac** [comment]
I have got it. Thank you very much.
