### ISSUE TITLE
About how to apply this work on my own data?

### ISSUE THREAD

**Issue by ZHyuwind** [mks0601/PoseFix_RELEASE#36]
First, thanks for your work. I want to apply your works on my own data, please tell me how to do?Thanks again!

**Comment by mks0601** [comment]
You can see [this code](https://github.com/mks0601/PoseFix_RELEASE/blob/master/data/COCO/dataset.py). Once you convert your dataset to MSCOCO format, you can easily adapt that code to use your dataset.

**Comment by ZHyuwind** [comment]
Thank you very much. I will try.&nbsp;



---Original---

**Comment by ZHyuwind** [comment]
Hello, I also meet a problem that my own dataset how to get annotations? or this file is not needed?Thanks.

**Comment by mks0601** [comment]
I cannot understand what you asked

**Comment by ZHyuwind** [comment]
> I cannot understand what you asked

sorry，maybe I need to understand how to transform dataset format again. I feel so sorry about disturbing you. Happy Christmas Eve！

**Comment by ZHyuwind** [comment]
Hello, I want to ask a question that my own data also need annotations file like COCO's person_keypoints_val2017.json?

**Comment by mks0601** [comment]
Right. You should convert annotation of your own dataset to MSCOCO format.

**Comment by mks0601** [comment]
Maybe these codes would be helpful. 
https://github.com/mks0601/TF-SimpleHumanPose/tree/master/tool

These codes convert mpii or posetrack datasets to coco format.

**Comment by ZHyuwind** [comment]
Thanks a lot, I will try!

**Comment by ZHyuwind** [comment]
Hello, I used coco2017val dataset  to get results from TF-simple pose, then take it as input_pose.json, but also appear "FileNotFoundError: [Errno 2] No such file or directory: 'tmp_result_0.pkl" ,I don't know how to deal with it. Please give me some advices, thank you very much!

**Comment by mks0601** [comment]
The `tmp_result_0.pkl` is a just temporal file, which is automatically generated during testing. You should set proper `dataset` and `testset` in `main/config.py` and proper path in `data/COCO/dataset.py`.

**Comment by ZHyuwind** [comment]
> The `tmp_result_0.pkl` is a just temporal file, which is automatically generated during testing. You should set proper `dataset` and `testset` in `main/config.py` and proper path in `data/COCO/dataset.py`.

Thank you, my problem has solved.

**Comment by lxy5513** [comment]
@mks0601 Hi, Could you please tell me how to generate `/test_on_trainset/result.json` in my own dataset.    
Could I produce it by `TF-SimpleHumanPose`?, It is indispensable? and what's it role?

**Comment by mks0601** [comment]
Most of the images do not have all keypoint coordinate annotations because of truncations or severe occlusions. I used `test_on_trainset` to fill the not annotated keypoint coordinates. The format of the `.json` file exactly follows [MSCOCO format](http://cocodataset.org/#format-results). You can use any human pose estimation method to get it.

**Comment by lxy5513** [comment]
@mks0601 Thanks your kind respond, Do you mean that original coordinate annotations may not include all keypoints, So the function of `test_on_trainset` is to mitigate the problem ?

**Comment by mks0601** [comment]
Yes. For example, the annotation file of COCO dataset contains `keypoints` like the below figure. 
![스크린샷, 2020-05-06 13-24-50](https://user-images.githubusercontent.com/13601723/81138485-303a8380-8f9d-11ea-9ff6-49aa0642a545.png)

Among `x1, y1, v1, ...`, `v1` provides the below information.
```
Each keypoint has a 0-indexed location x,y and a visibility flag v defined as v=0: not labeled (in which case x=y=0), v=1: labeled but not visible, and v=2: labeled and visible.
```
If v==0, the coordinates are not annotated, which requires `test_on_trainset`.

**Comment by lxy5513** [comment]
So kind of you, thanks!
