### ISSUE TITLE
calculate miss_prob , jitter_prob and inv_prob on other dataset

### ISSUE THREAD

**Issue by 965556810** [mks0601/PoseFix_RELEASE#37]
Thank you for your share.   I want to use your code on other dataset ( not keypoint of human ). I dont know how to Calculate the probility of miss , inversion and jitter in detail. Could you provide a little clue? Thanks~

**Comment by mks0601** [comment]
Hi, I didn't define and calculate the error statistics, but just borrowed them from Ronchi etal. (https://arxiv.org/abs/1707.05388).
Could you check this paper?
