### ISSUE TITLE
Statistics on latency and throughput

### ISSUE THREAD

**Issue by pigubaoza** [mks0601/PoseFix_RELEASE#38]
I would like to ask if there is any information on the model's latency and throughput on common GPUs and CPUs such as the Nvidia T4, Intel i7 CPU, etc

**Comment by mks0601** [comment]
Sorry I don't have NVIDIA T4. 

As I remember, ResNet152-384x288 model is quite heavy that it runs slow (maybe 5fps on GTX1080Ti).
If you use ResNet50-256x192 model, then I think it would be quite fast (maybe faster than 50fps on GTX1080Ti).
