### ISSUE TITLE
pre-train model? 

### ISSUE THREAD

**Issue by tianjiahao** [mks0601/PoseFix_RELEASE#4]
Traceback (most recent call last):
  File "test.py", line 220, in <module>
    test(int(args.test_epoch))
  File "test.py", line 192, in test
    result = MultiGPUFunc.work()
  File "/home/cv2018/Documents/PoseFix/main/../lib/tfflat/mp_utils.py", line 82, in work
    id, msg = load_pkl( 'tmp_result_{}'.format(self._proc_ids[i]) )
  File "/home/cv2018/Documents/PoseFix/main/../lib/tfflat/serialize.py", line 68, in load_pkl
    with open('{}.pkl'.format(name), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_result_0.pkl'

where can I download this 'pkl'? and how to solve this problem? thank you !

**Comment by mks0601** [comment]
That `pkl`file is temporal file in testing stage, which is generated by each GPU. Maybe you did some mistake about GPU numbering?

**Comment by tianjiahao** [comment]
Thanks to your reply, we only have one gpu(1080Ti) to test, so the problem arises in "python test.py --gpu 0 --test_epoch 140"。

**Comment by mks0601** [comment]
Sorry I haven't test this code on single GPU environment. I'll test and modify it.

**Comment by wonju2lee** [comment]
I have the same problem, could you please solve this issue or let me know the reason?

**Comment by mks0601** [comment]
Most (more than 90%) of this error comes from wrong configuration. Please check directories and `testset` in `config.py`.
