### ISSUE TITLE
About Fig.5 in your paper

### ISSUE THREAD

**Issue by Lixiuxiu2020** [mks0601/PoseFix_RELEASE#40]
Hi, @mks0601
Is the fifth column 'Heatmap' in Figure 5 from network output or softmax output?
Can you explain in detail how to draw 'Heatmap'. No relevant code was found on the project.

**Comment by mks0601** [comment]
I guess I got that by applying softmax on the network output.

**Comment by Lixiuxiu2020** [comment]
Thank you.
