### ISSUE TITLE
converting model to ONNX for C++ inference with TensorRT

### ISSUE THREAD

**Issue by khanhha** [mks0601/PoseFix_RELEASE#45]
Hello, thanks for your awesome project. 
I plan to convert your Tensorflow model to Onnx, and then load the converted Onnx model using TensorRT in C++ for real-time inference. 
I wonder if it's possible to do that using this framework https://github.com/onnx/tensorflow-onnx and your checkpoint?
Thanks

**Comment by mks0601** [comment]
Sorry, but I haven't used onnx :(

**Comment by khanhha** [comment]
Thanks for your response. I was able to do that. The inference in ONNX seems to produce correct results. The issue can be closed here.

**Comment by mks0601** [comment]
Good for you!
