### ISSUE TITLE
Is there any plan to provide pre-trained weights available?

### ISSUE THREAD

**Issue by daun-io** [mks0601/PoseFix_RELEASE#46]
I've read the paper you wrote and found that this model agnostic post-processing concept is really great and I think it would also work great with my pose estimation model too.
However since there is no pre-trained weights that are trained end-to-end as suggested your paper I cannot validate my model with posefix right away. Is there any plan to provide pre-trained weights?

Thanks!

**Comment by mks0601** [comment]
Which pre-trained weights do you want? I cannot get your question :( There is pre-trained PoseFix in the README.

**Comment by daun-io** [comment]
Oh I've read the README again and found the ResNet152 weights for posetrack2018 that I wanted to find. Sorry for disturbing and thanks for the fast answer :) 👍
