### ISSUE TITLE
inefficient heavy-CPU training

### ISSUE THREAD

**Issue by khanhha** [mks0601/PoseFix_RELEASE#47]
Hello, 

I would like to ask how much time did one epoch take when you trained the model? and how much time for training 140 epochs [the checkpoint you published]?

I have managed to bring up the training and it looks like that the GPU is idle most of the time. I guess it is due to the heavy-CPU pose synthesis code, as shown below

![image](https://user-images.githubusercontent.com/2276264/104746225-482eed80-574f-11eb-9871-cac1c823ac52.png)

According to my estimation, one COCO epoch is 9364 iterations. It takes 6 minutes to finish 30 iterations. This means 1 epoch will require 9364/30 * 6  = 1872.8 minutes = 31.2133333333 hours. That means it would take you around 150 days to finish 140 epochs right?

![image](https://user-images.githubusercontent.com/2276264/104746623-d4411500-574f-11eb-9847-d02354695219.png)

Thanks

**Comment by mks0601** [comment]
Whicih ResNet type and input size are you using? The running time of the log (13.00s r 0.02) tells you that GPU time is 13.00 second and cpu time is 0.02 second for each iteration. Maybe reducing the input image size to (256,192) and changing ResNet type to ResNet 50 would be good for your GPU. The error synthesize is very light and takes marginal computational cost.

**Comment by khanhha** [comment]
Thanks for your quick response

I use Resnet152 and the input size is 288x384. That's very strange because the GPU is idle most of the time and all of the CPUs are fully utilized [100% all of the time]. 

Can you tell me how long did one epoch take on your training machine?

**Comment by mks0601** [comment]
I can't remember clearly. I think Resnet 152 + 384x288 image took several days like two or three days? Maybe the training time is reported in the paper.

**Comment by khanhha** [comment]
Thank you very much. I will do a thorough training on my machine to see what is the problem. If there is anything new, I will post it here.

**Comment by khanhha** [comment]
hi, 
the slow training problem is because TensorFlow 1.5 doesn't work Cuda11.0 on my machine and TensorFlow 1.5 silently switches to CPU. 

Installing Cuda10, Cudnn 7.6.0 makes it work. The training is now very fast, 0.77 hours/epoch on a machine of 4 GPUs.

Thanks a lot for your support. The issue can be closed here.

**Comment by mks0601** [comment]
Good for you!

**Comment by zghn** [comment]
> hi, the slow training problem is because TensorFlow 1.5 doesn't work Cuda11.0 on my machine and TensorFlow 1.5 silently switches to CPU.
> 
> Installing Cuda10, Cudnn 7.6.0 makes it work. The training is now very fast, 0.77 hours/epoch on a machine of 4 GPUs.
> 
> Thanks a lot for your support. The issue can be closed here.

Hi,
I'm trying to run the train.py on GPU but I can't. I've installed CUDA 10. The output of nvcc --version confirm it.
But the output of nvidia-smi find CUDA 11.2 yet. My Ubuntu version is 22.04.
would you help me, please. What's the problem?
