### ISSUE TITLE
About training on MPII datasets

### ISSUE THREAD

**Issue by YuhaoCheng** [mks0601/PoseFix_RELEASE#5]
Hi, thanks for your work. However, I can't find the `mpii2coco.py`  in `tool` , and I'm confused that how to get the `input pose json`. Would you mind telling me how to get them? Thanks for your time.

**Comment by mks0601** [comment]
Sorry. You can see `mpii2coco.py` and `posetrack2coco.py` at [TF-SimpleHumanPose](https://github.com/mks0601/TF-SimpleHumanPose). I updated my README. Also, you can use pose estimation results of any other methods as `input_pose.json`.

**Comment by YuhaoCheng** [comment]
Thanks for apply, I will check the [TF-SimpleHumanPose](https://github.com/mks0601/TF-SimpleHumanPose). Thanks for you time.

**Comment by mks0601** [comment]
Perfect. Ask me if have any questions.
