### ISSUE TITLE
About the input_pose

### ISSUE THREAD

**Issue by YuhaoCheng** [mks0601/PoseFix_RELEASE#6]
Thanks  for your work and the patience.  I have encountered the error as follow:
```
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    trainer = Trainer(Model(), cfg)
  File "/export/home/cyh/PoseFix_RELEASE/main/../lib/tfflat/base.py", line 198, in __init__
    self._data_iter, self.itr_per_epoch = self._make_data()
  File "/export/home/cyh/PoseFix_RELEASE/main/../lib/tfflat/base.py", line 226, in _make_data
    with open(d.test_on_trainset_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/COCO/input_pose/test_on_trainset/result.json'
```
And I try to use the [TF-SimpleHumanPose](https://github.com/mks0601/TF-SimpleHumanPose) to generate the `test_on_trainset/result.json`, however, I found that you don't provide the detections results on the `train2017`. Would you mind offering the detcetions on that, or you could you please directly offer the `test_on_trainset/result.json` on `train2017`? Thanks for your time.

**Comment by mks0601** [comment]
You can download it in my README of PoseFix repo. Please refer to `Results` section.

**Comment by tianjiahao** [comment]
You have to set dataset, backbone and input_shape to those of the model in config.py.
    Pre-trained PoseFix model (COCO 2017, ResNet-152, 384x288) [model]
    Testing result on the COCO 2017 training set of TF-SimpleHumanPose [kps]
just download the 'kps'.

**Comment by YuhaoCheng** [comment]
OK. I got it. Thanks for your time.
